name: mc_sampling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.5
  - numpy=1.26.4
  - scikit-learn=1.5.1
  - matplotlib=3.9.2
  - scipy=1.13.1
  - concurrent.futures
  - multiprocessing
